### ISSUE TITLE
 GET https://ipinfo.io/AS3549: 401 { }

### ISSUE THREAD

**Issue by diwusec** [ipinfo/cli#100]
when i run 
diwusec@lol:~$ ipinfo AS3549
err: GET https://ipinfo.io/AS3549: 401 { }

i get this error and i have loged in using token also

**Comment by diwusec** [comment]
i have the latest version installed using go in ubuntu

diwusec@lol:~$ ipinfo version
2.8.0

and i signed up suing my gmail, after loging in i got a dashboard site, i opened dev tools and used console to get my token

i logged using this token : "IPinfoToken"

like this :

diwusec@lol:~$ ipinfo login
Enter token: 
logging in...
done

**Comment by UmanShahzad** [comment]
Ah yes, alright, makes sense. The issue is that the ASN API cannot be queried with a 'free' token. You'd have to purchase a plan that gives you ASN data, like the Basic plan - https://ipinfo.io/pricing

**Comment by diwusec** [comment]
oh actually i saw the github ipinfo where they had mentioned only about free token, which i thought it is free
 Get your token for free at https://ipinfo.io/signup i got this wrong

**Comment by diwusec** [comment]
sorry for reporting this as an issue and thanks for your time

**Comment by UmanShahzad** [comment]
Ah ok. No worries and thanks!
