### ISSUE TITLE
output error

### ISSUE THREAD

**Issue by binglin1009** [ipinfo/cli#105]
when running command on Windows, the output is unreadable, I think the reason is that Chinese is not supported. So, will it support Chinese in future?
![ipinfo](https://user-images.githubusercontent.com/58156930/165034392-512ba509-11e3-4c3f-93a9-1163e03e0e00.jpg)

**Comment by UmanShahzad** [comment]
@binglin1009 this is not Chinese. Those characters are color codes. The Windows terminal you're using doesn't support them, and ends up printing the raw textual form of them which looks like gibberish.

See https://github.com/ipinfo/cli#color-on-windows to help enable it. If it doesn't work you can also disable it - see https://github.com/ipinfo/cli#disabling-color-output
