### ISSUE TITLE
Windows 10 with Simplified Chinese is not supported?

### ISSUE THREAD

**Issue by binglin1009** [ipinfo/cli#125]
As below(the real IP is replaced with X.X.X.X):

C:\>ipinfo myip
Core
- [36mIP          [0m [32mX.X.X.X[0m
- [36mAnycast     [0m [32mfalse[0m
- [36mHostname    [0m [32m[0m
- [36mCity        [0m [32mShenzhen[0m
- [36mRegion      [0m [32mGuangdong[0m
- [36mCountry     [0m [32mChina (CN)[0m
- [36mLocation    [0m [32m22.5455,114.0683[0m
- [36mOrganization[0m [32mAS4134 CHINANET-BACKBONE[0m
- [36mPostal      [0m [32m[0m
- [36mTimezone    [0m [32mAsia/Shanghai[0m

**Comment by UmanShahzad** [comment]
See https://github.com/ipinfo/cli#color-on-windows - those are color codes not rendering properly.
