### ISSUE TITLE
ipinfo does show something else in the output

### ISSUE THREAD

**Issue by reben-f5** [ipinfo/cli#126]
I've downloaded ipinfo tool with PS script and installed it but when i type: ipinfo myip or 8.8.8.8 does show something else instead (please see attachment).

Will you please be able to provide step-by-step instruction to get this one right?

<img width="382" alt="ipinfo" src="https://user-images.githubusercontent.com/59086062/210542152-295645c1-f061-40c5-a032-0b225567445c.png">

**Comment by UmanShahzad** [comment]
See https://github.com/ipinfo/cli#color-output

**Comment by reben-f5** [comment]
sorry - what does that respond even mean?

**Comment by reben-f5** [comment]
never mind use your tool with awful help, thanks
