### ISSUE TITLE
Country flag emoji oddly displayed

### ISSUE THREAD

**Issue by yermulnik** [ipinfo/cli#144]
There was a new feature introduced in https://github.com/ipinfo/cli/pull/124 (related issue: https://github.com/ipinfo/cli/issues/123) to show country flag emoji. This doesn't work as intended in my terminal app and shows country code oddly:
![image](https://user-images.githubusercontent.com/1274789/233049619-25fa3b2b-78ea-41e8-8b6f-cee6d10f7e86.png)
I tested with different terminal apps and this either shows oddly or doesn't show up at all based on chosen font. Some fonts do stretch this "emoji" so letters don't overlap, some don't. I really would appreciate this to be togglable. Thank you.

**Comment by yermulnik** [comment]
The other way around might be to allow or filter out some fields, which `--field` option seems to be designed for, though it doesn't work with pretty format and switches output to CSV 😢
The "filter out" option looks better as it would allow newly introduced fields to be shown up by default, which improves UX.

**Comment by UmanShahzad** [comment]
Pushed https://github.com/ipinfo/cli/commit/02e2503b7d0c38b0f1fa031edfceaedd41383aff - we'll release this soon.

**Comment by yermulnik** [comment]
@UmanShahzad Thanks a bunch!

**Comment by yermulnik** [comment]
Is there any timeline on the nearest release? This weirdness with flag is a bit annoying 😢

**Comment by UmanShahzad** [comment]
We've got a lot more changes coming along with that in the pipeline, so will be doing a significant release very soon. Stay tuned!

**Comment by yermulnik** [comment]
@UmanShahzad Any at least approx timeline? It make s `ipinfo` semi unusable to me =(

**Comment by UmanShahzad** [comment]
@yermulnik just released 3.0.0 which has this fix 👍

**Comment by yermulnik** [comment]
Yay! Appreciate that! 🕺🏻

**Comment by yermulnik** [comment]
Looking forward for the Brew tap to get this update soon 🤞🏻
