### ISSUE TITLE
Releasing v1

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/cli#17]
The package's feature set looks and feels ready for a v1 release. But we need to do the following:

- **Make the repository public.**
- Upload 1.0.0 tag/binaries (currently only beta versions released).

Right after the repo is public, we can:

- Upload to homebrew; we need the repo's public URL to download & install the CLI when homebrew runs.

There may be things you guys have planned @coderholic @kennethkhaw like a blog or something. I'm not in the loop on that so, if that's a blocker let me know.

**Comment by coderholic** [comment]
We're now public! 🍾 

@UmanShahzad best way to make an animated gif of usage? Is there a tool that takes a script / text input, and makes a gif or something?

**Comment by coderholic** [comment]
https://terminalizer.com/ looks good

**Comment by UmanShahzad** [comment]
Oh that looks nice, I'll try adding something to the README header area!

**Comment by UmanShahzad** [comment]
How's this? If you have some other ideas of a workflow lemme know and I can record that.

![render1617672200243](https://user-images.githubusercontent.com/10018065/113645741-e2446900-96a0-11eb-8159-e72e3834e134.gif)

**Comment by coderholic** [comment]
@UmanShahzad love it! I'd like to include some examples of cat-ing a log into it, and summarizing too. And also doing an example where we lookup the hostnames for a bunch of IPs using the field argument. Might make sense to break these into a few different examples.

**Comment by UmanShahzad** [comment]
Good idea, I especially agree this would be best to break into multiple GIFs. I'll look to upload some really nice examples over the weekend.

**Comment by UmanShahzad** [comment]
Added a bunch to the quick-start section: https://github.com/ipinfo/cli#quick-start

Lemme know what to add/del/update!

**Comment by UmanShahzad** [comment]
Will close the issue since v1 is released; the GIFs can be improved at any time.

**Comment by coderholic** [comment]
@UmanShahzad did you use terminalizer? Do you have the script / input file that can be used to adjust the gif?

cc @st-polina - we should "launch" the cli on twitter whenever there's a free slot (think it's map this week, birthday promo week after, so maybe week after that?)

**Comment by UmanShahzad** [comment]
@coderholic Oh yes forgot to mention that: all the GIF files & their configs are in https://github.com/ipinfo/cli/tree/master/gif

It's not *that* easy to edit unfortunately, but it can be done and then re-generated.

**Comment by st-polina** [comment]
@coderholic sounds good!
@UmanShahzad can we have a call next week Thursday or Friday to prepare for the announcement the week after? I have some very noob questions around CLI :D It'd be great to do a blog post and a social media post.

**Comment by UmanShahzad** [comment]
@st-polina Yes of course, just send me an invite link any time. I think our timezones are fairly close so any time during normal working hours should be good (minus 12pm-2:30pm GMT+5 Friday).
