### ISSUE TITLE
Windows 11 (Defender): Trojan:Win32/Bearfoos.B!ml Trojan Virus 

### ISSUE THREAD

**Issue by jozuekupec** [ipinfo/cli#175]
Hello,
there is an issue with app on windows 11. Windows Defender moves the app into quarantine and it is recognized as Trojan virus.
Should I add this app to exceptions list or is there better way how to handle it?

**Comment by UmanShahzad** [comment]
Also you can report this false positive to Microsoft from the defender app, if that's possible. That'll help them improve their detection.

**Comment by UmanShahzad** [comment]
See e.g. https://superuser.com/questions/1416678/my-own-backup-program-was-detected-as-win32-bearfoos-aml-virus
