### ISSUE TITLE
Piping a list of IP addresses to map and summarize is NOT working

### ISSUE THREAD

**Issue by evild3ad** [ipinfo/cli#177]
Piping a list of IP addresses to map and summarize is bogus in v3.1.0 (ipinfo_3.1.0_windows_amd64.zip).

IPinfo.io CLI throws following error message:
err: not ip

Please fix! Thx!

**Comment by UmanShahzad** [comment]
Thanks for catching that. Fixed in https://github.com/ipinfo/cli/commit/504f4874fb67706da7d8ca10ee4cbadc851233ba

We'll upload a new version with 3.1.1 soon!
