### ISSUE TITLE
"ipinfo tool aggregate" weirdness

### ISSUE THREAD

**Issue by yermulnik** [ipinfo/cli#187]
I might be do something wrong, though it looks like `ipinfo tool aggregate` does nothing for me 😢 
```shell
> terraform output -json | jq -r '.output | .value| .[] | select(. | startswith("172"))'
172.17.0.0/16
172.25.0.0/16
172.26.0.0/16
172.27.0.0/16
172.28.0.0/16
172.29.0.0/16

> terraform output -json | jq -r '.output | .value| .[] | select(. | startswith("172"))' | ipinfo tool aggregate
172.17.0.0/16
172.25.0.0/16
172.26.0.0/16
172.27.0.0/16
172.28.0.0/16
172.29.0.0/16

> terraform output -json | jq -r '.output | .value| .[] | select(. | startswith("172"))' | aggregate -q
172.17.0.0/16
172.25.0.0/16
172.26.0.0/15
172.28.0.0/15
```
Is it me or the tool?

**Comment by talhahwahla** [comment]
Hey, thanks for pointing that -- the issue seems to be with the tool.

Looks like `ipinfo tool aggregate` works only  for the prefixes that are included in other prefixes:
```
$ ipinfo tool aggregate 203.97.2.0/24 203.97.0.0/17
203.97.0.0/17
```

It doesn't appear to aggregate the adjacent prefixes:

```
$ ipinfo tool aggregate 203.97.2.0/24 203.97.3.0/24 
203.97.2.0/24
203.97.3.0/24
# should be 203.97.2.0/23
```
We should do this latter optimization too -- taking a note, will get to it

**Comment by UmanShahzad** [comment]
@yermulnik we just merged an update on the main branch - not sure how you install but if you can use `go install` on the main branch and try and let us know that'd be great.

Will release a new patch soon too.

**Comment by yermulnik** [comment]
@UmanShahzad Worked like a charm (apart from Golang having no reverse option for `go install`)! Thanks
```bash
> terraform output -json | jq -r '.output | .value| .[] | select(. | startswith("172"))' | ipinfo tool aggregate
172.17.0.0/16
172.25.0.0/16
172.26.0.0/15
172.28.0.0/15
```
