### ISSUE TITLE
API endpoint for usage

### ISSUE THREAD

**Issue by bladeswords** [ipinfo/cli#197]
Hi ipinfo team,

I have yet to find an API endpoint for showing my usage information.  I know this can be fetched on the dashboard page. However, I want to check the usage of the API quota programmatically.  I note that the `/account/home/` data returned on the dashboard is in JSON, but perhaps a little verbose for general usage information.

Would this be a feature on the roadmap, or is there something I am missing?

Thanks!

**Comment by shrink** [comment]
@bladeswords the `/me` endpoint might be what you're looking for, i.e:

```
https://ipinfo.io/me?token=example
```

Does this work for you?

**Comment by UmanShahzad** [comment]
The CLI provides `ipinfo quota` for this too, FYI. Uses the sam `/me` endpoint.

**Comment by bladeswords** [comment]
@shrink and @UmanShahzad - thank you both very much!  I was looking for this everywhere in the ipinfo API documentation and could not find it anywhere.
