### ISSUE TITLE
Tool → aggregate function throwing error at file input

### ISSUE THREAD

**Issue by abdullahdevrel** [ipinfo/cli#198]
- OS: Ubuntu (WSL)
- CLI version: `3.2.0`, `3.1.0`

The first input contains CIDR values. 

> cidrs.txt

```
1.1.1.0/30
1.1.1.0/28
```

The command I have tried out:

```bash
ipinfo tool aggregate cidrs.txt 

```
Output:

```
Invalid CIDR: 1.1.1.0/30
1.1.1.0/28
```
---

I tried with a set of IP addresses contained in a file next.

> cidrs.txt

```bash
2.160.52.0
2.160.52.4
2.160.52.8
```

Output

```
cat ./cidrs.txt | ipinfo tool aggregate
Invalid input: 2.160.52.0
Invalid input: 2.160.52.4
```

----

- OS: Mac OS
- CLI version: `3.2.0`

Later, I tried the command in Mac OS. And it worked.

```
anyfactor@ipinfo cli_test % cat cidrs.txt
1.1.1.0/30
1.1.1.0/28

anyfactor@ipinfo cli_test % ipinfo tool aggregate cidrs.txt
1.1.1.0/28

anyfactor@ipinfo cli_test % ipinfo tool aggregate 1.1.1.0/30 1.1.1.0/28
1.1.1.0/28
```

**Comment by Taimoor-12** [comment]
The latest version has been released that addresses these issues. Please install that.
