### ISSUE TITLE
Tool → `aggregate` function does not print IPs as is

### ISSUE THREAD

**Issue by abdullahdevrel** [ipinfo/cli#199]
System

- OS: Mac OS, Ubuntu
- CLI Version: 3.2.0

In the help output of the `aggregate` function, it states.

> If input contains single IPs, it tries to merge them into the input CIDRs, otherwise they are printed to the output as they are.

However, in its current implementation, it does not do that.

```
anyfactor@ipinfo cli_test % ipinfo tool aggregate 89.224.56.209 15.25.106.76 160.57.73.173 21.246.12.156 118.28.172.45 13.99.97.68 135.145.235.208 155.228.4.2 50.111.74.162 204.144.192.129

anyfactor@ipinfo cli_test %
```

**Comment by Taimoor-12** [comment]
The fixes for the aggregate tool have not yet gone live but will be, soon. In the meanwhile, you can try installing using `go install ./ipinfo/` to get the latest version and try running the aggregate command again with these inputs

**Comment by abdullahdevrel** [comment]
Hey @Taimoor-12,

Thanks for reviewing the issue. From which branch should I install the tool?

In the `master` git branch, I can see that the last commit was made two weeks ago, which was before I opened the ticket.

https://github.com/ipinfo/cli/blob/master/lib/cmd_tool_aggregate.go

**Comment by Taimoor-12** [comment]
We suggested a temporary solution to install the CLI from the root directory of the project and test the same commands but now you can try installing the latest CLI version `3.3.0` released today that addresses the issues with the `aggregate` tool.

**Comment by abdullahdevrel** [comment]
@Taimoor-12  Awesome. I tried to install the CLI, and came across this issue: https://github.com/ipinfo/cli/issues/201

So, I will wait to try out the function properly after resolving that issue. In the meanwhile, can you tell me why the issue failed to run properly, please? I would love to know.

**Comment by Taimoor-12** [comment]
It failed to run because the version you were using did not have fixes for the tool incorporated. The new version, i.e., `3.3.0`, incorporates the changes for the tool to work correctly. As #201 has been resolved, you can now try out the function properly and let us know if it works as expected!
