### ISSUE TITLE
Improve pretty output

### ISSUE THREAD

**Issue by coderholic** [ipinfo/cli#20]
We improved the summary output dramatically in https://github.com/ipinfo/cli/issues/7 but the pretty output for IP and ASN is still super high contrast, and could be improved:

![image](https://user-images.githubusercontent.com/26079/113089898-7001ef00-919d-11eb-9934-cca7ec882634.png)

(oh, actually looks like the ASN output is always raw json)

**Comment by UmanShahzad** [comment]
Assuming this is good enough 👍
