### ISSUE TITLE
Different GLIBC version in 3.3.0?

### ISSUE THREAD

**Issue by willpower232** [ipinfo/cli#202]
I use the static binaries so I can back up my life a bit better

Version 3.2.0 - works great

Version 3.3.0 - complains about missing GLIBC

Has there been a build time error or am I missing a dependency I wasn't aware of?

![image](https://github.com/ipinfo/cli/assets/1619102/6bd980da-b694-457d-86a4-866cf20065e4)

**Comment by abu-usama** [comment]
@willpower232 Thank you for reporting this.
I didn't face this problem on Ubuntu 22.04. Could you please provide some details about your setup?

**Comment by willpower232** [comment]
I'm currently on Zorin OS 16.3 which I believe is partly Ubuntu 20.04 and partly Ubuntu 22.04.

Apparently I have glibc 2.31

![image](https://github.com/ipinfo/cli/assets/1619102/b5c9feac-5b51-4a72-8099-17c08efc2521)

I do need to find the time to upgrade to Zorin OS 17 and it seems glibc has a 3 year lifecycle so is apparently already out of date for me so this might be out of your reasonable ability to support.

**Comment by abu-usama** [comment]
Closing this. @willpower232  Please feel free to open another issue if the problems persists after upgrade.
