### ISSUE TITLE
Map feature deprecated?

### ISSUE THREAD

**Issue by evild3ad** [ipinfo/cli#228]
Your awesome map feature is not showing any country icons and country names? Issue?

I am using your "Free" subscription plan and IPinfo CLI v3.3.1 on Windows x64.

![Map-Issue](https://github.com/user-attachments/assets/3f85834c-e002-4df7-ba32-415ef3e1162f)

**Comment by shrink** [comment]
That's not intentional, definitely a bug on the website. I'll take a look at what the cause might be. Apologies for the inconvenience!

**Comment by evild3ad** [comment]
Thank you very much for the fast response!

**Comment by shrink** [comment]
Thank you for reporting the issue, I have identified the cause and the fix is being deployed. I'll update this ticket once the fix is live, in about 30 minutes.

**Comment by evild3ad** [comment]
Works again! 😃 

Awesome tool and awesome support! Thx! 💪
