### ISSUE TITLE
ANSI-colour on Windows

### ISSUE THREAD

**Issue by gvanem** [ipinfo/cli#25]
I probably assume that you assume all consoles on Windows handles
ANSI-sequences. Mine does, but I've turned that off for various reasons.
And I'm now left with this junk output:
```
f:\MingW32\src\inet\IP-geo\IPinfo-CLI>ipinfo.exe  8.8.8.8
Core
- ←[36mIP          ←[0m ←[32m8.8.8.8←[0m
- ←[36mAnycast     ←[0m ←[32mtrue←[0m
- ←[36mHostname    ←[0m ←[32mdns.google←[0m
- ←[36mCity        ←[0m ←[32mMountain View←[0m
- ←[36mRegion      ←[0m ←[32mCalifornia←[0m
- ←[36mCountry     ←[0m ←[32mUnited States (US)←[0m
- ←[36mLocation    ←[0m ←[32m37.4056,-122.0775←[0m
- ←[36mOrganization←[0m ←[32mAS15169 Google LLC←[0m
- ←[36mPostal      ←[0m ←[32m94043←[0m
- ←[36mTimezone    ←[0m ←[32mAmerica/Los_Angeles←[0m
```

Could someone in 2021 please detect that such codes are effective before using them?
AFAIK, a `GetConsoleMode()` and test for `ENABLE_VIRTUAL_TERMINAL_PROCESSING` should do it.
Ref:  https://docs.microsoft.com/en-us/windows/console/getconsolemode

Otherwise this is pretty cool program.

**Comment by Calinou** [comment]
The coloring is handled by fatih/color, so I doubt the CLI developers have any control over this.

All we could do is obey the `NO_COLOR` environment variable and disable colors if it's set to 1.

**Comment by UmanShahzad** [comment]
@gvanem I imagine this'd be an issue for any terminal emulator which either doesn't support or has disabled via config the interpreting of these codes. So the solution you're recommending isn't generic enough and we'll likely get another issue later for a different emulator.

I'll just add a flag & `NO_COLOR` env var support as @Calinou mentioned to disable outputting color codes, and you can turn that on.

As a side note:

> Could someone in 2021 please detect that such codes are effective before using them?

This attitude is unwarranted. We'll make the change, but you could word it more respectfully.

**Comment by gvanem** [comment]
> Could you explain why? 

Since I use 4NT as my shell (since 20 years ago). Microsloth's `cmd` is just crap.

**Comment by glittle** [comment]
Is this related to the "pretty" format?  

Apparently that is on by default, and can be turned on with  -p

Is there a way to turn it off?

**Comment by glittle** [comment]
On a fresh install of Windows 10, I see the ANSI codes.

**Comment by gvanem** [comment]
> On a fresh install of Windows 10, I see the ANSI codes.

Since the VT-emulation is default. But like I wrote, those new VT-console functions messes up my shell big time.

But I tried to modify `vendor\github.com\mattn\go-colorable\colorable_windows.go` to disable this non-sense.
But rebuilding `ipinfo.exe` fails; none of the steps in `README.md` works. Just obscure errors like:
`build github.com/ipinfo/cli/ipinfo: cannot load io/fs: malformed module path "io/fs": missing dot in first path element`.

**Comment by UmanShahzad** [comment]
> Is this related to the "pretty" format?

@glittle No, but if you use json/csv format then no colors will be displayed.

> Just obscure errors like

@gvanem Nothing obscure about it. Your golang installation isn't right.

**Comment by UmanShahzad** [comment]
Added support for the `--nocolor` flag and the `NO_COLOR` environment variable in https://github.com/ipinfo/cli/releases/tag/ipinfo-1.1.1

Let me know if there's still any issues.

**Comment by wasi-master** [comment]
You can see [this comment on stackoverflow](https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences#comment92954461_16799175) to enable ANSI escape sequences in the windows terminal, I tried this myself and it works. I think this should be in the readme

**Comment by UmanShahzad** [comment]
@wasi-master Interesting, can you make a PR?

**Comment by wasi-master** [comment]
@UmanShahzad PR with what exactly? editing the readme to include this?

**Comment by UmanShahzad** [comment]
@wasi-master Yes, if you want.

**Comment by wasi-master** [comment]
I think I'll just wait till https://github.com/ipinfo/cli/pull/24 is merged
