### ISSUE TITLE
Support for ARM architecture?

### ISSUE THREAD

**Issue by paulgfrey** [ipinfo/cli#27]
Just wondering if there are plans to support the ARM architecture.

**Comment by UmanShahzad** [comment]
We can easily support it, just wasn't initially sure of the demand. Will make it available in the next release.

**Comment by UmanShahzad** [comment]
Should be available in https://github.com/ipinfo/cli/releases/tag/ipinfo-1.1.1 - let me know if there are issues getting it to work.
