### ISSUE TITLE
Make binary available via OS distribution repositories

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/cli#3]
We can distribute the binary for each platform via Github initially so it can be installed with `curl`/`wget`/etc, but it'd be even better if developers (the most likely users here) could grab it via their OS distributor's package repo. This could give us auto-completion automatically as well without a separate install step for that.

We can start with making it available via Ubuntu's package repos first, and/or make our own PPA.

I don't use macOS so not sure of the distribution model there (I think most people use Homebrew?), but we can look into that afterwards.

**Comment by UmanShahzad** [comment]
Now that the repo is public I'll try to make this available in Homebrew.

Making it available in official Linux distributions is gonna be a *much* harder task, and likely not worth it when you can just `curl` or `wget` the binary, so we probably shouldn't bother.

**Comment by UmanShahzad** [comment]
Well this is annoying: someone already took the name "ipinfo" in the official Homebrew repo: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ipinfo.rb

Not sure what else we could name it. I think we'll need to use a custom "Tap" and put our own formula there.

**Comment by st-polina** [comment]
@UmanShahzad we use ipinfoio on Twitter as an alternative to ipinfo if it helps :)

**Comment by UmanShahzad** [comment]
@st-polina We can try that yeah, but the binary's name is actually `ipinfo` so it will conflict with the existing formula which outputs it as `ipinfo` too. There's no requirement that the binary name be `ipinfo` at all though.

At this point I'm just thinking it might be 10x better to just create a single script that the user downloads and it gets automatically run, and then it downloads the appropriate binary on its own regardless of platform (Windows would still be different though).

**Comment by mbierman** [comment]
@UmanShahzad i disagree that a script would be better. Homebrew isn’t just the standard for macOS installation. It keeps things up to date complete with dependencies. I run a script regularly to update all my homebrew packages and apps. I personally don’t care if the name is ideal. Having a  homebrew install would be extremely nice.

**Comment by UmanShahzad** [comment]
@mbierman that's a good point, thanks for the feedback. That mostly settles it then for me, I'd say: let's try to get this on Homebrew even if under a different name.

**Comment by mbierman** [comment]
Thanks, @UmanShahzad!

**Comment by yermulnik** [comment]
Also please consider adding an option for installation via `go get …`

**Comment by UmanShahzad** [comment]
@yermulnik It should work already: https://github.com/ipinfo/cli#using-go-get

**Comment by karlhorky** [comment]
If this works on Windows as well, I would recommend making available on Chocolatey and `winget`.

**Comment by UmanShahzad** [comment]
It definitely works, and will look into that, thanks!

**Comment by yermulnik** [comment]
> @yermulnik It should work already: https://github.com/ipinfo/cli#using-go-get

oops, apologies, somehow I missed that bit 🤦  thanks a lot for the pointer 🙇

**Comment by UmanShahzad** [comment]
@yermulnik Oh no you didn't miss it, I just added it because you mentioned it :) Thanks to you!

**Comment by hellopablo** [comment]
My suggestion for the homebrew formula name: `ipinfo-cli`; I don't _think_ that _has_ to translate into the binary name. You can [define conflicting formulae](https://docs.brew.sh/Formula-Cookbook#specifying-conflicts-with-other-formulae), too.

**Comment by mbierman** [comment]
@UmanShahzad please post here when Homebrew is ready and I'll give it a try.

**Comment by yermulnik** [comment]
> @UmanShahzad please post here when Homebrew is ready and I'll give it a try.

+1. I'd like it for both Mac and Linux and can test on both.

**Comment by UmanShahzad** [comment]
Thanks guys, I'll ping you when we have something. I'll try working on getting it on Homebrew one way or another over the weekend.

**Comment by UmanShahzad** [comment]
For anyone with homebrew, please try this and let me know if it works (it works for me on macos & linux):

```bash
brew install ipinfo/tap/ipinfo-cli

# optionally:
brew install ipinfo/tap/grepip
```

ref: https://github.com/ipinfo/cli#macos

**Comment by hellopablo** [comment]
Works perfectly on macOS 11.3 👏

**Comment by mbierman** [comment]
Seems good on macOS 10.15.7.

**Comment by UmanShahzad** [comment]
Thanks a lot for checking guys, going to close this issue and track windows/linux package managers specifically in #30 and #31 respectively.

**Comment by coderholic** [comment]
Not a smooth install for me...

```
$ brew install ipinfo/tap/ipinfo-cli
==> Installing ipinfo-cli from ipinfo/tap
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.16.3
Already downloaded: /Users/bendowling/Library/Caches/Homebrew/downloads/a0c7d5540c8c88f612cedc7d9af128deb15aa152ce0b0f2e1bcd3d8f235020f5--go-1.16.3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:69c28f5e60612801c66e51e93d32068f822b245ab83246cb6cb374572eb59e15
Already downloaded: /Users/bendowling/Library/Caches/Homebrew/downloads/d74822e0d6c473f04ff2856cab284c0f3a55bc4edbd09f63f4c542a528d0495e--go--1.16.3.catalina.bottle.tar.gz
==> Downloading https://github.com/ipinfo/cli/archive/ipinfo-1.1.1.tar.gz
Already downloaded: /Users/bendowling/Library/Caches/Homebrew/downloads/2e7919969ed33530ce59bd398c2d5012d7595682b0647299d98ee8ee9cce00a0--cli-ipinfo-1.1.1.tar.gz
Error: The following formula cannot be installed from bottle and must be
built from source.
  ipinfo-cli
Install the Command Line Tools:
  xcode-select --install

```

After doing the xcode-select install it worked...

```
$ brew install ipinfo/tap/ipinfo-cli
==> Installing ipinfo-cli from ipinfo/tap
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.16.3
Already downloaded: /Users/bendowling/Library/Caches/Homebrew/downloads/a0c7d5540c8c88f612cedc7d9af128deb15aa152ce0b0f2e1bcd3d8f235020f5--go-1.16.3.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/go/blobs/sha256:69c28f5e60612801c66e51e93d32068f822b245ab83246cb6cb374572eb59e15
Already downloaded: /Users/bendowling/Library/Caches/Homebrew/downloads/d74822e0d6c473f04ff2856cab284c0f3a55bc4edbd09f63f4c542a528d0495e--go--1.16.3.catalina.bottle.tar.gz
==> Downloading https://github.com/ipinfo/cli/archive/ipinfo-1.1.1.tar.gz
Already downloaded: /Users/bendowling/Library/Caches/Homebrew/downloads/2e7919969ed33530ce59bd398c2d5012d7595682b0647299d98ee8ee9cce00a0--cli-ipinfo-1.1.1.tar.gz
==> Installing dependencies for ipinfo/tap/ipinfo-cli: go
==> Installing ipinfo/tap/ipinfo-cli dependency: go
==> Pouring go--1.16.3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/go/1.16.3: 9,955 files, 503.5MB
==> Installing ipinfo/tap/ipinfo-cli
==> ./ipinfo/build.sh
🍺  /usr/local/Cellar/ipinfo-cli/1.1.1: 5 files, 7.3MB, built in 5 seconds
```

How can we have it "installed from bottle"? And ideally it should be possible to `brew install ipinfo-cli` instead of needking to know about our tap. How can we get that setup @UmanShahzad ?

**Comment by UmanShahzad** [comment]
@coderholic Installing from a "bottle" means installing the binary directly without a build step, but that means doing a ton of CI for lots of different macos versions (and linux for linuxbrew users) to auto-build and auto-update the SHA-256 checksums of each binary for each platform, and upload them to github (this has some other complications - it's not a github "release" like we do in this repo). It's possible to do, will just take quite some more time.

This can be simplified if we were on the official Homebrew tap because they already have all this CI set up, but it may take a while to get accepted by them, and then there are statements like these in [their docs](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Formulae.md#niche-or-self-submitted-stuff):

> We frown on authors submitting their own work unless it is very popular.
> ...
> Even if all criteria are met we may not accept the formula. Documentation tends to lag behind current decision-making. Although some rejections may seem arbitrary or strange they are based on years of experience making Homebrew work acceptably for our users.

In the interest of getting this available to our users right now I've made our own tap. But if we really want installations to be possible via "bottles", then we'd best try to get this on the official tap. Homebrew has a "tap migration" feature so that once it's available on the official tap, all users on our current tap can automatically get migrated over there.

**Comment by yermulnik** [comment]
JFYI: have just successfully upgraded `ipinfo-cli` from `1.1.1` to `1.1.2` on both MacOS and Linux 🥳

**Comment by UmanShahzad** [comment]
@yermulnik Good to know that upgrades are working as intended, thank you!

**Comment by UmanShahzad** [comment]
Made https://github.com/Homebrew/homebrew-core/pull/77280 to try and get this into the official tap now.

**Comment by UmanShahzad** [comment]
Now available on the official homebrew tap:

```bash
brew install ipinfo-cli
```

Will get the remaining formulas up there as well e.g. for `grepip`.

**Comment by yermulnik** [comment]
> Now available on the official homebrew tap:

:+1: Anything we should do to adhere to this change? Like re-installing?

**Comment by UmanShahzad** [comment]
@yermulnik You'll automatically get migrated to the official version, nothing special to do! Just use `ipinfo-cli` instead of `ipinfo/tap/ipinfo-cli` whenever you upgrade.

You can remove the old tap if you don't want it: `brew untap ipinfo/tap`

**Comment by yermulnik** [comment]
Got that! Thanks @UmanShahzad 
Will keep the old tap unless you've got `grepip` moved to the official brew formulaes repo. Or even for any new tool you may add to it in future =)

**Comment by UmanShahzad** [comment]
Yes sure, will notify when `grepip` is on Homebrew, then will close this issue.

https://github.com/Homebrew/homebrew-core/pull/77397 is the PR for grepip.

**Comment by mbierman** [comment]
Thank you @UmanShahzad !

**Comment by UmanShahzad** [comment]
If you are using grepip then this should work going forward:

```bash
brew install grepip
```

**Comment by yermulnik** [comment]
Thank you @UmanShahzad !
