### ISSUE TITLE
Myip only returns core on macOS

### ISSUE THREAD

**Issue by mbierman** [ipinfo/cli#32]
```
bigmac:bin michael$ ipinfo myip
Core
- IP           147.**.*.*
- Anycast      false
- Hostname     *****
- City         Santa Clara
- Region       California
- Country      United States (US)
- Location    
- Organization AS396097 Sail Internet, Inc.
- Postal       9***
- Timezone     America/Los_Angeles
```

**Comment by UmanShahzad** [comment]
@mbierman You need to apply your token via e.g. logging in with `ipinfo login` or using `-t` or `--token` per command.

**Comment by mbierman** [comment]
Doesn't change anything. 
bigmac:bin michael$ ipinfo login 
Enter token: {entered}
logged in
bigmac:bin michael$ ipinfo myip
Core
- IP           147.**.**.*
- Anycast      false
- Hostname     ***
- City         Santa Clara
- Region       California
- Country      United States (US)
- Location     ***
- Organization AS396097 Sail Internet, Inc.
- Postal       9***
- Timezone     America/Los_Angeles

**Comment by UmanShahzad** [comment]
@mbierman Then that means your token is only allowed core data specifically. For more data fields you'd need to trial/purchase it on ipinfo.io.

Or if you actually see more data via curl with the same token, then let me know.

**Comment by mbierman** [comment]
O.K. that wasn't clear from the documentation. Thanks!

**Comment by UmanShahzad** [comment]
Noted, thanks, will update the README with that somewhere.
