### ISSUE TITLE
ASN input returning an error

### ISSUE THREAD

**Issue by coderholic** [ipinfo/cli#42]
Reported via twitter: https://twitter.com/philBE2/status/1395060460127494147

```
$ ipinfo as15169
err: GET https://ipinfo.io/AS15169: 401 { }
$ ipinfo AS15169
err: GET https://ipinfo.io/AS15169: 401 { }
```

https://ipinfo.io/AS15169 is a legit ASN

**Comment by UmanShahzad** [comment]
The ASN API requires a token, so it's returning a 401 because of not being authorized.

Similar to the batch issue (https://github.com/ipinfo/cli/issues/35) - will make the error more graceful so the user knows to enter their token.

**Comment by UmanShahzad** [comment]
Fixed by https://github.com/ipinfo/cli/commit/05ff7d64342c14984f38ffc909ea8e6e4c001303 and released in https://github.com/ipinfo/cli/releases/tag/ipinfo-1.1.4
