### ISSUE TITLE
Shell auto-completion

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/cli#5]
In the initial version we won't have proper shell auto-completion.

There exist some completion frameworks in Golang but they were too buggy and/or didn't support our flag format.

Most preferable would be finding a tool that auto-generates some completion script in whatever language (doesn't have to be Golang), and we include it in the package.

**Comment by yermulnik** [comment]
Much desirable addition to the great tool of the great service! Thanks!

**Comment by UmanShahzad** [comment]
Hmm turns out even the package I mentioned isn't really meant for public use. I'm forking the original project into https://github.com/ipinfo/complete and working on modifying it to work with the POSIX flag format.

**Comment by UmanShahzad** [comment]
This will be released in v2 which should be out next week, hopefully.

**Comment by yermulnik** [comment]
`ipinfo --help` is missing bits re shell completion — is this by design?

**Comment by UmanShahzad** [comment]
It's actually there but seems that a bug in the completion library fork causes subcommands to be recommended only instead of the flags. Will look into fixing that. https://github.com/ipinfo/cli/issues/47

**Comment by yermulnik** [comment]
Apart from the bug you mentioned I mean that help message doesn't list `completion` as a subcommand:
```
> ipinfo --help | fgrep -c comple
0
```

**Comment by UmanShahzad** [comment]
Oh thanks for catching that, you're right. https://github.com/ipinfo/cli/commit/0c1acc6e5be1c8f057ca61bb09f9570fb7be5d7c solves it and I'll try to release a 2.0.1 with the fix.

**Comment by UmanShahzad** [comment]
https://github.com/ipinfo/cli/releases/tag/ipinfo-2.0.1 and will be on homebrew soon.

**Comment by yermulnik** [comment]
Marvelous! Thank you @UmanShahzad :bow:
