### ISSUE TITLE
[feature/grepip] Provide an option to match CIDR blocks and IP ranges

### ISSUE THREAD

**Issue by T145** [ipinfo/cli#61]
Presently the utility would just return an IP defined at the start of a CIDR block or the IPs on either end of an IP range.

It would be great to have options that match these formats, or have such a functionality be the default.

**Comment by UmanShahzad** [comment]
Yeah it'd be great for sure. Will keep it in mind.

**Comment by UmanShahzad** [comment]
Should be covered by https://github.com/ipinfo/cli/pull/185
