### ISSUE TITLE
Dont cache `myip`

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/cli#88]
We seem to be caching `myip` by default from what I can tell, which is probably not what we want almost ever, because using that command you're explicitly looking to see what your current IP is, which may have changed.

**Comment by elbarbudo** [comment]
You are right ! It is confusing because I start and stop a VPN and used ipinfo myip to check the connection..
My previous command was curl -Ss -w '\n' https://ipinfo.io?token=xxxxxxxx and I expected that ipinfo myip gives me the same result, which is NOT the case.

**Comment by rm-Umar** [comment]
Works fine for me, it's not caching `myip` anymore. It was fixed in #114. I think we should release the new version as the last release `2.8.1` was on May 23 and the PR was merged on Jul 20.
