### ISSUE TITLE
Accept requests via IPv6

### ISSUE THREAD

**Issue by whoisroot** [ipinfo/cli#97]
The service already returns information when queried about IPv6 addresses, but only accepts requests over IPv4. It would be useful if the `myip` command returned IPv6 addresses.

I tried querying the API via IPv6 with cURL, but the domain does not have an _AAAA_ record on the DNS.

Sometimes IPv6 routes are different from IPv4 ones and faster. This could also help to ease the adoption of IPv6 globally.

**Comment by UmanShahzad** [comment]
@whoisroot can you try against `v6.ipinfo.io`?

**Comment by thamet** [comment]
https://github.com/ipinfo/cli/issues/97#issue-1179594438
